### ISSUE TITLE
An error when using Quick start example - Uncaught TypeError: $ is not a function

### ISSUE THREAD

**Issue by jarifuri** [boxing/boxrec#255]
Hello,
I tried to use the quick start example:
```jsx
const boxrec = require("boxrec").Boxrec;
const cookieJar = await boxrec.login('jarifuri', 'xxxxxxxx');
```
and got the following error during the request:
```jsx
await boxrec.getPersonById(cookieJar, 352);
```

> Uncaught TypeError: $ is not a function  
   at step (/home/random/node_modules/boxrec-requests/dist/boxrec-requests.js:32:23)                                                                                                  
   at Function.<anonymous> (/home/random/node_modules/boxrec-requests/src/boxrec-requests.ts:597:36)

I already used boxrec package in the past, so I corrected my scripts to be in line with the new version (7.1.4) but I got the same error as above.

**Comment by jesseigb** [comment]
The error is still persistent. I assume that when running a function like getPersonByID the cookieJar that is being passed is actually a Promise<pending> instead of the Cookie itself.

const cookieJar = async () => {
    let a = await boxrec.login([USER], [PASSWORD]);
    console.log(a);
    return a;
}

The console.log(a) displays the inside of the cookieJar, most importantly the PHPSESSID which is what I assume all functions are asked to be passed.

However if you try to call the cookieJar function like this "console.log(cookieJar());" it still returns a Promise<pending> instead of the inside of the CookieJar which means that all the function of the API will return the TypeError as the CookieJar isn't actually being passed.

Any suggestions?

**Comment by mikedidomizio** [comment]
@jesseigb perhaps your error is different if I'm reading your code snippet correctly.  What should be done in your case is something like this:

```typescript
(async() => {
    // the cookieJar returned from the login method holds the PHPSESSID
    const cookieJar = await boxrec.login(BOXREC_USERNAME, BOXREC_PASSWORD);
    // afterwards, any requests require the cookieJar to be passed in as a parameter
    const response = await boxrec.getPersonById(cookieJar, 352);  // note at this time this will throw an error.
})();
```

**Comment by mikedidomizio** [comment]
Everyone try an update to `boxrec@7.1.5`?

This should work now but there are some information now missing or hidden from BoxRec.

For instance, they used to display the "date of birth" or `born` on a profile page, which they don't now.  If you query that information you will get `null`.

```
const response = await boxrec.getPersonById(cookieJar, 348759);
console.log(response.alias);        // Canelo
console.log(response.nationality);  // Mexico
console.log(response.division);     // super middleweight
console.log(response.born);         // null
```

I think this should unblock people, I haven't had the time to properly test all methods.

Let me know if that works.

**Comment by jesseigb** [comment]
TypeError: $ is not a function error still happening even after update to boxrec@7.1.5

**Comment by mikedidomizio** [comment]
I think there is/was an issue with packing the package it uses, therefore try `boxrec@7.1.6`.  Thanks for your patience.  I tried it through the registry myself and it does appear fixed.

**Comment by jarifuri** [comment]
Hi Mike,
I reinstall the package and the issue disappeared. Thanks a lot for the solving the issue.

**Comment by mikedidomizio** [comment]
Awesome, thanks for letting me know.
